# Generated by Django 5.0.3 on 2024-03-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('atmosphericPressure', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
